/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bulldog.gltf --transform 
Files: bulldog.gltf [24.9MB] > bulldog-transformed.glb [513.7KB] (98%)
Author: Frank.Zwick (https://sketchfab.com/Frank_Zwick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-b-1of13-for-free-435bab21e6494be28fd4106e58772674
Title: DOG B - 1of13 - for free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bulldog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Muffin_N_50k_4k_2022_e_Muffin_N_50k_4k_2022_e_u0_v0_0.geometry} material={materials.Muffin_N_50k_4k_2022_e_u0_v0} position={[0.491, 0.006, 0]} rotation={[-1.576, 1.56, Math.PI / 2]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/bulldog-transformed.glb')
