/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 erath.gltf --transform 
Files: erath.gltf [41.6MB] > erath-transformed.glb [4.14MB] (90%)
Author: denis_cliofas (https://sketchfab.com/denis_cliofas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-3684eb40fb7e42208089874e6286b9e9
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/erath-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.002}>
          <group name="Earth" rotation={[-Math.PI / 2, 0, 0]} scale={57.393}>
            <mesh name="Earth_Earth_0" geometry={nodes.Earth_Earth_0.geometry} material={materials.Earth} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/erath-transformed.glb')
