/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 html_logo.gltf --transform 
Files: html_logo.gltf [20.61KB] > html_logo-transformed.glb [10.72KB] (48%)
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html-logo-3d-model-ab8b32cab3364027ab00a033a0b2ff38
Title: HTML logo 3d model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/html_logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.009']} position={[-10.526, 117.48, 18.962]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.010']} position={[-10.526, 117.48, 24.052]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.011']} position={[-10.526, 117.48, 24.052]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.012']} position={[-23.565, 209.044, 42.712]} rotation={[0, 0, -Math.PI / 2]} scale={100} />
    </group>
  )
}

useGLTF.preload('/html_logo-transformed.glb')
